services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - laravel-storage-production:/var/www/storage:ro
      - laravel-public-assets:/var/www/public/build:ro
    networks:
      - laravel-production
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      php-fpm:
        condition: service_started

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - laravel-public-assets:/var/www/public/build
      - laravel-storage-production:/var/www/storage
    env_file:
      - .env
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      meilisearch:
        condition: service_started

  mariadb:
    image: mariadb:12
    ports:
      - "${MARIADB_PORT:-3306}:3306"
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE:-app}
      - MARIADB_USER=${MARIADB_USER:-laravel}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-secret}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-root}
    volumes:
      - mariadb-data-production:/var/lib/mysql
    networks:
      - laravel-production

  redis:
    image: redis:8.6-alpine
    restart: unless-stopped
    networks:
      - laravel-production
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:4.2-alpine
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq-data-production:/var/lib/rabbitmq
    networks:
      - laravel-production
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterkey}
    volumes:
      - meilisearch-data-production:/meili_data
    networks:
      - laravel-production
    ports:
      - "${MEILISEARCH_PORT:-7700}:7700"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  queue-import-orchestrator:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - laravel-public-assets:/var/www/public/build
      - laravel-storage-production:/var/www/storage
    env_file:
      - .env
    networks:
      - laravel-production
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["php", "artisan", "queue:work", "--queue=import-orchestrator"]

  queue-import-chunks:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - laravel-public-assets:/var/www/public/build
      - laravel-storage-production:/var/www/storage
    env_file:
      - .env
    networks:
      - laravel-production
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["php", "artisan", "queue:work", "--queue=import-chunks"]
    deploy:
      mode: replicated
      replicas: 2

  queue-import-finalize:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - laravel-public-assets:/var/www/public/build
      - laravel-storage-production:/var/www/storage
    env_file:
      - .env
    networks:
      - laravel-production
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["php", "artisan", "queue:work", "--queue=import-finalize"]

  queue-scout:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - laravel-public-assets:/var/www/public/build
      - laravel-storage-production:/var/www/storage
    env_file:
      - .env
    networks:
      - laravel-production
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["php", "artisan", "queue:work", "--queue=scout"]

networks:
  laravel-production:

volumes:
  mariadb-data-production:
  laravel-storage-production:
  laravel-public-assets:
  meilisearch-data-production:
  rabbitmq-data-production:
